JasperRazorTest/JasperRazorTest/Controllers/RazorTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JasperRazorTest.Controllers
{
    public class RazorTestController : Controller
    {
        //
        // GET: /RazorTest/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Test()
        {
            return View();
        }

        public ActionResult CalTest()
        {
            return View();
        }

        public ActionResult JqueryListViewDemo2()
        {
            return View();
        }

	}
}

JasperRazorTest/JasperRazorTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
  
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script>
        $(document).ready(function () {
            $('ul.nav li.dropdown').hover(function(){
                $(this).children('ul').slideDown(200); 
            }, function(){
                $(this).children('ul').slideUp(200); 
            })

            $(".caret").click(function () {
                alert("Working");
            })           
        });
        $(function () {
            //alert("Running");
        });
    </script>

    <link rel="stylesheet" type="text/css" href="~/Content/custom.css">

    @*<script src="~/JQGridReq/jquery-1.9.0.min.js" type="text/javascript"></script>*@

    <script src="~/JQGridReq/jquery.jqGrid.js" type="text/javascript"></script>
    <link href="~/JQGridReq/ui.jqgrid.css" rel="stylesheet" type="text/css" />

    <script src="~/JQGridReq/grid.locale-en.js" type="text/javascript"></script>
    <script src="~/JQGridReq/jquery-ui-1.10.4.custom.js" type="text/javascript"></script>
    @*<script src="~/Content/jquery.jqGrid.fluid.js" type="text/javascript"></script>*@
    <link href="~/Content/main.css" rel="stylesheet" type="text/css">
    <link href="~/JQGridReq/jquery-ui-1.10.4.custom.css" rel="stylesheet" type="text/css" />

    <!-- Context Menu Src-->
    <script src="~/ContextMenuSrc/jquery.ui.position.js" type="text/javascript"></script>
    <script src="~/ContextMenuSrc/jquery.contextMenu.js" type="text/javascript"></script>
    <link href="~/ContextMenuSrc/jquery.contextMenu.css" rel="stylesheet" type="text/css" />




</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top navbar-JJ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("JasperRazerIndex", "Index", "RazorTest")</li>
                    <li>@Html.ActionLink("JasperRazerTest", "Test", "RazorTest")</li>
                    <li>@Html.ActionLink("JasperCalTest", "CalTest", "RazorTest")</li>
                    <li><a href="#contact">Contact</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown 2 <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

      
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>